Repository jxoffline/jxtools, pull requests merged in 2023-10, with the labels that each got.

#4 Thêm webtool ShopBuilder
  shopbuilder/assets/files/server1.zip
  shopbuilder/assets/jquery.csv.js
  shopbuilder/bundle.d1e7876ecf8aba76729d.js
  shopbuilder/bundle.d1e7876ecf8aba76729d.js.LICENSE.txt
  shopbuilder/index.html
  shopbuilder/source/.gitignore
  shopbuilder/source/README.md
  shopbuilder/source/package-lock.json
  shopbuilder/source/package.json
  shopbuilder/source/src/assets/jquery.csv.js
  shopbuilder/source/src/common/cache.js
  shopbuilder/source/src/common/events.js
  shopbuilder/source/src/common/ui/buysell_editor.js
  shopbuilder/source/src/common/ui/goods_editor.js
  shopbuilder/source/src/common/ui/index.js
  shopbuilder/source/src/common/ui/index.scss
  shopbuilder/source/src/common/ui/items_viewer.js
  shopbuilder/source/src/common/ui/magicscript_editor.js
  shopbuilder/source/src/global.js
  shopbuilder/source/src/index.html
  shopbuilder/source/src/index.js
  shopbuilder/source/src/index.scss
  shopbuilder/source/src/libs/fileManager.js
  shopbuilder/source/src/libs/helpers.js
  shopbuilder/source/src/libs/index.js
  shopbuilder/source/src/libs/vConverter.js
  shopbuilder/source/webpack.config.js
  shopbuilder/source/webpack.config.prod.js
Labels: story

#5 Cập nhật tập tin hướng dẫn và cấu hình CDCI cho ShopBuilder tool
  .DS_Store
  README.md
  shopbuilder.d/bundle.d1e7876ecf8aba76729d.js
  shopbuilder.d/bundle.d1e7876ecf8aba76729d.js.LICENSE.txt
  shopbuilder.d/index.html
  shopbuilder/.DS_Store
  shopbuilder/source/README.md
Labels: cicd

#6 Cấu hình .gitignore toàn cục ở thư mục gốc
  .gitignore
  shopbuilder/source/.gitignore
Labels: cicd

#7 Làm sạch các tập tin cached files từ Mac
  .DS_Store
  shopbuilder/.DS_Store
Labels: cicd

#8 Cập nhật video hướng dẫn sử dụng Youtube
  shopbuilder/source/README.md
Labels: documentation

#9 Cập nhật video hướng dẫn sử dụng Youtube
  shopbuilder/source/README.md
Labels: documentation

#10 Create static.yml
  .github/workflows/static.yml
Labels: cicd

#11 Cập nhật liên kết ứng dụng shopbuiler
  shopbuilder/source/README.md
Labels: documentation

#12 Di chuyển README ra vị trí dễ tìm hơn
  README.md
  shopbuilder/README.md
Labels: documentation
